config/routes.rb
Rails.application.routes.draw do
  root 'barbecues#index'

  resources :barbecues, only: [ :index, :show, :new, :create ]
end

app/models/barbecue.rb
class Barbecue < ActiveRecord::Base
  validates :title, presence: true
  validates :venue, presence: true
  validates :date, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/barbecues_controller.rb
class BarbecuesController < ApplicationController
  def index
    @barbecues = Barbecue.order(:date)
  end

  def show
    # Don't add any code to this show action.
    # Implement your barbecue API in another action.
  end

  def new
    @bbq = Barbecue.new
  end

  def create
    bbq_params = params.require(:barbecue).permit(:title, :venue, :date)
    @bbq = Barbecue.new(bbq_params)

    unless @bbq.save
      render(:new)
    else
      redirect_to(barbecues_path)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/barbecues_helper.rb
module BarbecuesHelper
  def format_date(date)
    return date.strftime('%B, %e %Y at %l:%M %P')
  end
end

app/views/barbecues/index.html.erb
<h1>BBQs</h1>

<a href="<%= new_barbecue_path %>" class="btn btn-primary">
  Add a new BBQ
</a>

<ul class="list-unstyled">
  <% @barbecues.each do |bbq| %>
    <li data-bbq="<%= bbq.id %>">
      <h2>
        <a href="<%= barbecue_path(bbq.id) %>">
          <%= bbq.title %>
        </a>
      </h2>

      <dl>
        <dt>Date:</dt>
        <dd><%= format_date(bbq.date) %></dd>
        <dt>Venue:</dt>
        <dd><%= bbq.venue %></dd>
      </dl>

      <button class="btn btn-success" data-hook="join-bbq">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
        Join <%= bbq.title %>
      </button>
    </li>
  <% end %>
</ul>

app/views/barbecues/new.html.erb
<h1>Add a new BBQ</h1>

<% if @bbq.errors.any? %>
  <ul class="list-unstyled">
    <% @bbq.errors.full_messages.each do |msg| %>
      <li class="alert alert-danger" role="alert"><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @bbq do |form| %>
  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :venue %>
    <%= form.text_field :venue, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :date %>
    <%= form.date_field :date, class: 'form-control' %>
  </div>

  <button type="submit" class="btn btn-success">
    Add BBQ
  </button>
<% end %>

app/views/barbecues/show.html.erb
<h1>BBQ</h1>

<div data-hook="bbq-info" data-bbq="<%= params[:id] %>"></div>

<a href="<%= barbecues_path %>">Back to list of BBQs</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Barbecues</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application', defer: true %>
  <%= csrf_meta_tags %>
</head>
<body data-hook="controller-<%= controller_name %> action-<%= action_name %>">

  <div class="container">
    <%= yield %>
  </div>

</body>
</html>